### ISSUE TITLE
"no database connection" on start when configuring by workspace/configuration

### ISSUE THREAD

**Issue by oblitum** [lighttiger2505/sqls#59]
**Describe the bug**

I currently use `workspace/configuration` instead of configuration files and the server is always emitting the `"no database connection"` error message on start, but the server does works regardless.

**To Reproduce**
1. Use a `workspace/configuration` config. An example one I use to set coc.nvim in neovim 0.5 is:
    ```lua
    vim.fn['coc#config']('languageserver.sqls', {
        command = 'sqls',
        filetypes = { 'sql' },
        settings = {
            sqls = {
                connections = {
                    {
                        driver = 'postgresql',
                        dataSourceName = 'postgres://postgres@localhost/database?sslmode=disable'
                    }
                }
            }
        }
    })
    ```

**Expected behavior**

I don't expect this message to show up.

**Versions (please complete the following information):**
 - OS Version: Arch Linux
 - sqls Version sqls Version:0.2.18, Revision:db8733f

**Additional context**

**Comment by waydegg** [comment]
I'm also having the same issue, however I'm using Neovim's LSP config instead of COC.

**Comment by cizordj** [comment]
Me too, but I'm using lunarvim. This is the config that I setup with `:LspSettings sqls`

```json
{
  "settings": {
    "sqls": {
      "connections": [
        {
          "driver": "postgresql",
          "proto": "unix",
          "user": "postgres",
          "passwd": "password",
          "dbName": "omitted"
        },
        {
          "driver": "postgresql",
          "proto": "unix",
          "user": "postgres",
          "passwd": "password",
          "dbName": "omittedAsWell"
        }
      ]
    }
  }
}
```

**Comment by PhilVince96** [comment]
> I'm also having the same issue, however I'm using Neovim's LSP config instead of COC.

Me as well. :/

**Comment by Cih2001** [comment]
I had the same issue, and I fixed it by setting up the global config. It seems that it ignores all other methods. to fix create the config file on `~/.config/sqls/config.yml`:

```
# Set to true to use lowercase keywords instead of uppercase.
lowercaseKeywords: false
connections:
  - alias: psql
    driver: postgresql
    dataSourceName: 'host=127.0.0.1 port=5432 user=postgres password=secret dbname=testdb sslmode=disable'
```
